# .github/workflows/build.yml
name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      # docker_image_tag: ${{ steps.set_output.outputs.image_tag }}
      image_name: ${{ steps.set_outputs.outputs.image_name }}
      image_tag: ${{ steps.set_outputs.outputs.image_tag }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        id: build
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/my-python-app
          IMAGE_TAG=$(echo $GITHUB_SHA | cut -c1-7)
          docker build -t $IMAGE_NAME:$IMAGE_TAG .
          docker push -t $IMAGE_NAME:$IMAGE_TAG
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Set outputs
        id: set_outputs
        run: |
          echo "image_name=${IMAGE_NAME}" >> $GITHUB_ENV
          echo "image_tag=${IMAGE_TAG}" >> $GITHUB_ENV
          echo "::set-output name=image_name::${IMAGE_NAME}"
          echo "::set-output name=image_tag::${IMAGE_TAG}"

      # - name: Build and push Docker image
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: .
      #     tags: ${{ secrets.DOCKER_USERNAME }}/my-python-app:${{ github.sha }}
      #     push: true

      # - name: Set Docker image tag output
      #   id: set_output
      #   run: echo "image_tag=${{ github.sha }}" >> $GITHUB_ENV
         
