# .github/workflows/build.yml
name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      docker_image_tag: ${{ steps.set_output.outputs.image_tag }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: ${{ secrets.DOCKER_USERNAME }}/my-python-app:${{ github.sha }}
          push: true

      - name: Set Docker image tag output
        id: set_output
        run: echo "image_tag=${{ github.sha }}" >> $GITHUB_ENV
         
        