# .github/workflows/main.yml
name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  generate-dynamic-var:
    runs-on: ubuntu-latest
    outputs:
      dynamic-var: ${{ steps.set-output.outputs.dynamic-var }}
    steps:
      - name: Generate dynamic variable
        id: set-output
        run: |
          echo "dynamic-var-value=$(date +%s)" >> $GITHUB_ENV
          echo "::set-output name=dynamic-var::$(date +%s)"

      - name: Echo dynamic variable
        run: echo "O Valor da Variavel é :" ${{steps.set-output.outputs.dynamic-var}}

      - name: Ler variavel Github env
        run: echo "O Valor da variavel é ${{ env.dynamic-var-value }}"


  call-reusable-workflow:
    needs: generate-dynamic-var
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      dynamic-var: ${{ needs.generate-dynamic-var.outputs.dynamic-var }}