# .github/workflows/main.yml


on:
  push:
    branches:
      - main

jobs:
  generate-dynamic-var:
    runs-on: ubuntu-latest
    outputs:
      dynamic-var: ${{ steps.set-output.outputs.dynamic-var-value }}
    steps:
      - name: Generate dynamic variable
        id: set-output
        run: |
          echo "dynamic-var-value=$(date +%s)" >> $GITHUB_OUTPUT

      - name: Echo dynamic variable
        run: echo "O Valor da Variavel é :" ${{ steps.set-output.outputs.dynamic-var-value }}

  call-reusable-workflow:
    needs: generate-dynamic-var
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      dynamic-var: ${{ needs.generate-dynamic-var.outputs.dynamic-var }}


