# .github/workflows/reusable-workflow.yml
name: Reusable Workflow

on:
  workflow_call:
    inputs:
      dynamic-var:
        required: true
        type: string

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print dynamic variable
        run: echo "The dynamic variable is ${{ inputs['dynamic-var'] }}"
