name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Export SHA tag
        run: echo "IMAGE_TAG=${{ github.sha }}" >> $GITHUB_ENV
