name: Deploy

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: build
    outputs:
      image_tag: ${{ needs.build.outputs.image_tag }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3


    - name: Echo image name and tag
      run: |
        echo "Deploying image: ${{ needs.build.outputs.image_tag }}"

