name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3


    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Generate image tag
      id: tag
      run: echo "IMAGE_TAG=${{ secrets.DOCKER_USERNAME }}/myapp:${{ github.sha }}" >> $GITHUB_ENV

    - name: Export image tag as output
      id: export_tag
      run: echo "IMAGE_TAG=${{ secrets.DOCKER_USERNAME }}/myapp:${{ github.sha }}" >> $GITHUB_ENV

    outputs:
      image_tag: ${{ steps.export_tag.outputs.IMAGE_TAG }}
