name: Use Tag

on:
  workflow_run:
    workflows: ["Create Tag"]
    types:
      - completed

jobs:
  use_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Retrieve the tag from previous workflow
        run: echo "Tag from previous workflow is ${{ github.event.workflow_run.outputs.tag_value }}"
