name: Create Tag

on:
  push:
    branches:
      - main

jobs:
  create_tag:
    runs-on: ubuntu-latest
    outputs:
      tag_value: ${{ steps.set_tag.outputs.tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create a new tag
        id: set_tag
        run: |
          TAG="v1.0.0"
          echo "::set-output name=tag::${TAG}"

      - name: Persist the tag in outputs
        run: echo "TAG=$TAG" >> $GITHUB_ENV
