name: Build

on:
  workflow_call:
    outputs:
      tag:
        description: Tag image
        value: ${{ jobs.build.outputs.tag }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.build.outputs.tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy
        id: build
        run: |
          echo "tag=${GITHUB_SHA}" >> $GITHUB_ENV
          echo "::set-output name=tag::${GITHUB_SHA}"
