name: Define Variables
on:
  workflow_dispatch:
  push:
    branches:
      - main


jobs:
  define-vars:
    runs-on: ubuntu-latest
    outputs:
      account: ${{ steps.set-vars.outputs.account }}
      service: ${{ steps.set-vars.outputs.service }}
      cluster: ${{ steps.set-vars.outputs.cluster }}
      application: ${{ steps.set-vars.outputs.application }}
      deployment_group: ${{ steps.set-vars.outputs.deployment_group }}
      container_name: ${{ steps.set-vars.outputs.container_name }}
    steps:
      - name: Set Variables
        id: set-vars
        run: |
          echo "account=conta-dev" >> $GITHUB_ENV
          echo "service=srv-01" >> $GITHUB_ENV
          echo "cluster=lab-ecs" >> $GITHUB_ENV
          echo "application=my-app" >> $GITHUB_ENV
          echo "deployment_group=my-group-app" >> $GITHUB_ENV
          echo "container_name=svc-my-app" >> $GITHUB_ENV
          echo $GITHUB_ENV